### ISSUE TITLE
M3.simple-todos-react deploy 헤로쿠 Deploy

### ISSUE THREAD

**Issue by 88minkim** [Entrepreneurship-bootcamp-02/M-storybook#18]

**Comment by 88minkim** [comment]
![deploy](https://cloud.githubusercontent.com/assets/22495452/19218886/68091cfc-8e40-11e6-8d6d-50602ee444ac.PNG)
![desktop heroku deploy](https://cloud.githubusercontent.com/assets/22495452/19218887/6a3e5410-8e40-11e6-9808-3d020fb08275.PNG)
![mobile heroku deploy](https://cloud.githubusercontent.com/assets/22495452/19218942/37480988-8e41-11e6-9cff-ac0c8c9303ec.jpg)

**Comment by dkmin** [comment]
@88minkim 브라보, 잘 하셨습니다!
